# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 08:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='letter',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-Z]$', 'Only a captial letter is allowed.')], verbose_name='Problem ID'),
        ),
    ]
