# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='number',
            field=models.CharField(default=1, max_length=1, validators=[django.core.validators.RegexValidator('^[A-Z]$', 'Only Captial letter allowed.')]),
            preserve_default=False,
        ),
    ]
