# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_timelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
