# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-Z]$', 'Only Captial letter is allowed.')]),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_ID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
