# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='phase',
        ),
    ]
