# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_contest_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_ID',
        ),
    ]
