# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_score_accepteda'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='acceptedB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='acceptedC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='acceptedD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='acceptedE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='acceptedF',
            field=models.IntegerField(default=0),
        ),
    ]
