# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20171021_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
