# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_score_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='acceptedA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='acceptedB',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='acceptedC',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='acceptedD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='acceptedE',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='acceptedF',
            field=models.BooleanField(default=False),
        ),
    ]
