# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=1, upload_to='<function Profile.<lambda> at 0x7f4efde87730>/'),
            preserve_default=False,
        ),
    ]
