# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 08:19
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='/static/default_picture.jpg', upload_to=accounts.models.path),
        ),
    ]
