# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='<function Profile.<lambda> at 0x7f9e3973c730>/'),
        ),
    ]
