# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 06:37
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171018_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to=accounts.models.path),
        ),
    ]
