# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.5 on 2017-10-02 12:39
=======
# Generated by Django 1.11.5 on 2017-10-02 10:47
>>>>>>> update_stuff
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemid', models.CharField(max_length=10)),
                ('userid', models.CharField(max_length=160)),
<<<<<<< HEAD
                ('submission_time', models.DateTimeField(default=datetime.datetime(2017, 10, 2, 12, 39, 49, 537610, tzinfo=utc))),
=======
                ('submission_time', models.DateTimeField(default=datetime.datetime(2017, 10, 2, 10, 47, 28, 39752, tzinfo=utc))),
>>>>>>> update_stuff
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('C', 'Completed')], default='P', max_length=1)),
                ('lang', models.CharField(choices=[('C++', 'C++'), ('Java', 'Java'), ('C', 'C'), ('Py2', 'Python 2'), ('Py3', 'Python 3')], default='C', max_length=4)),
                ('testcases_passed', models.IntegerField(default=0)),
                ('verdict', models.CharField(default='Pending', max_length=20)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Queue')),
            ],
        ),
    ]
