# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 10, 57, 32, 566919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('P', 'Passed'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
