# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20171003_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='lang',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 12, 11, 15, 301312, tzinfo=utc)),
        ),
    ]
