# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20171002_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='queue_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 11, 51, 3, 489712, tzinfo=utc)),
        ),
    ]
