# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20171019_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('Q', 'In queue'), ('R', 'Running'), ('WA', 'Wrong Answer'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('AC', 'Accepted'), ('TLE', 'Time Limit Exceeded')], default='Q', max_length=2),
        ),
    ]
