# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20171003_1400'),
        ('judge', '0003_auto_20171003_1741'),
    ]

    operations = [
    ]
