# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_merge_20171003_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('cpp', 'C++'), ('java', 'Java'), ('c', 'C'), ('py', 'Python 2'), ('py3', 'Python 3')], default='cpp', max_length=4),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 14, 27, 44, 213683, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('WA', 'Wrong Answer'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('AC', 'Accepted')], default='AC', max_length=1),
        ),
    ]
