# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20171003_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
