# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20171003_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 10, 3, 14, 40, 18, 340922, tzinfo=utc)),
        ),
    ]
